import { Prisma } from '@prisma/client';

export const currencySelect = {
  id: true,
  code: true,
  name: true,
  symbol: true,
  decimals: true,
  isActive: true,
  isDefault: true,
  createdAt: true,
} satisfies Prisma.CurrencySelect;

export const personBasicSelect = {
  id: true,
  customerNo: true,
  fullName: true,
  phone: true,
  address: true,
  externalId: true,
  notes: true,
  category: true,
  status: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
} satisfies Prisma.PersonSelect;

const receivedCardOperationSelect = {
  id: true,
  cardId: true,
  operationType: true,
  categoryCode: true,
  categoryFaceValue: true,
  quantity: true,
  amount: true,
  balanceBefore: true,
  balanceAfter: true,
  progressBefore: true,
  progressAfter: true,
  note: true,
  reason: true,
  userId: true,
  username: true,
  occurredAt: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
} satisfies Prisma.ReceivedCardOperationSelect;

const receivedCardStageLogSelect = {
  id: true,
  cardId: true,
  stage: true,
  direction: true,
  amount: true,
  note: true,
  userId: true,
  username: true,
  createdAt: true,
} satisfies Prisma.ReceivedCardStageLogSelect;

export const receivedCardEmbeddedSelect = {
  id: true,
  batchId: true,
  sequence: true,
  publicCode: true,
  bankName: true,
  cardLast4: true,
  valueUsd: true,
  agreedAmount: true,
  settlementCurrencyId: true,
  settlementAmount: true,
  settlementPaymentMethod: true,
  receivedAmount: true,
  status: true,
  verificationReceived: true,
  secureInternalNote: true,
  notes: true,
  totalDeducted: true,
  remainingAmount: true,
  progressPercent: true,
  currentStage: true,
  rejectedAt: true,
  rejectReason: true,
  cardThumbnailDataUrl: true,
  cardImageMimeType: true,
  cardImageSize: true,
  cardImageUpdatedAt: true,
  archivedAt: true,
  deletedAt: true,
  createdAt: true,
  updatedAt: true,
  settlementCurrency: { select: currencySelect },
  operations: {
    where: { deletedAt: null },
    orderBy: [{ occurredAt: 'desc' }, { createdAt: 'desc' }],
    take: 12,
    select: receivedCardOperationSelect,
  },
  stageLogs: {
    orderBy: { createdAt: 'desc' },
    take: 8,
    select: receivedCardStageLogSelect,
  },
} satisfies Prisma.ReceivedCustomerCardSelect;

export const receivedCardResponseSelect = {
  ...receivedCardEmbeddedSelect,
  batch: {
    select: {
      id: true,
      personId: true,
      currencyId: true,
      entryTransactionId: true,
      receivedAt: true,
      cardCount: true,
      agreedAmountPerCard: true,
      totalOriginalAmount: true,
      totalAgreedAmount: true,
      notes: true,
      createdByUserId: true,
      createdByUsername: true,
      createdAt: true,
      updatedAt: true,
      person: { select: personBasicSelect },
      currency: { select: currencySelect },
    },
  },
} satisfies Prisma.ReceivedCustomerCardSelect;

export const personDetailSelect = {
  ...personBasicSelect,
  cardBatches: {
    select: {
      id: true,
      personId: true,
      currencyId: true,
      entryTransactionId: true,
      receivedAt: true,
      cardCount: true,
      agreedAmountPerCard: true,
      totalOriginalAmount: true,
      totalAgreedAmount: true,
      notes: true,
      createdByUserId: true,
      createdByUsername: true,
      createdAt: true,
      updatedAt: true,
      currency: { select: currencySelect },
      cards: {
        where: { deletedAt: null },
        orderBy: { sequence: 'asc' },
        select: receivedCardEmbeddedSelect,
      },
    },
    orderBy: { receivedAt: 'desc' },
  },
  cardDeliveries: {
    where: { deletedAt: null },
    orderBy: { occurredAt: 'desc' },
    select: {
      id: true,
      personId: true,
      currencyId: true,
      paymentMethod: true,
      amount: true,
      balanceBefore: true,
      balanceAfter: true,
      reason: true,
      note: true,
      userId: true,
      username: true,
      occurredAt: true,
      createdAt: true,
      updatedAt: true,
      deletedAt: true,
      currency: { select: currencySelect },
    },
  },
} satisfies Prisma.PersonSelect;

export const receivedCardBatchResponseSelect = {
  id: true,
  personId: true,
  currencyId: true,
  entryTransactionId: true,
  receivedAt: true,
  cardCount: true,
  agreedAmountPerCard: true,
  totalOriginalAmount: true,
  totalAgreedAmount: true,
  notes: true,
  createdByUserId: true,
  createdByUsername: true,
  createdAt: true,
  updatedAt: true,
  person: { select: personBasicSelect },
  currency: { select: currencySelect },
  cards: {
    where: { deletedAt: null },
    orderBy: { sequence: 'asc' },
    select: receivedCardEmbeddedSelect,
  },
} satisfies Prisma.ReceivedCardBatchSelect;
